server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH:}
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DATABASE:pgazienda}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST} 
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL}
    from: ${MAIL_FROM}    
    baseurl: ${MAIL_BASEURL}
  messages:
    basename: i18n/messages
    
# SWAGGER
swagger:
   title: Play&Go Aziendale API
   description: API for the company management and user association
   version: 1.0.0
   license: Apache License, Version 2.0
   licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
   contact:
      name: Smart Community Lab
      url: www.smartcommunitylab.it
      email: info@smartcommunitylab.it


app:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: ${SECURITY_SECRET:bgYh3rbvGzbJKK/q7k624Ct360QuA4IHHO8jBtMUKA/spqu+BMLkktWpiQuBMXuoVxBYOUwWnBvLXnizzrhKFyJkX9gf9gU6+L8tJl6D1VjAwh8w/iwqiubqmmMSSRxdmu7rmFWLlSi3HpumEfsIzagI2TiPI2U2pCn27vn2TAthiUXELXusVYe3r9awz2DQP/V10yi3j9AIh0Gslz89yUjY6tmrQ8RcJSApvo4FGBdK1EzZU/6CZaEFvmPQEx3I8TG26Y8pVqfcuR+OELhLQ2iOfP5ZlwQiom4UmkNdbMh4ZLyfSN0C9anZojYnpSBym6N8XOQo+7Ueqgpm0w0dFw==}
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
    ext:
      endpoint-userinfo: ${SECURITY_EXT_USERINFO_ENDPOINT}
      username-field: ${SECURITY_EXT_USERINFO_USERNAME_FIELD:username}
      name-field: ${SECURITY_EXT_USERINFO_NAME_FIELD:first_name}
      surname-field: ${SECURITY_EXT_USERINFO_SURNAME_FIELD:last_name}
      domain: ${SECURITY_EXT_USERINFO_DOMAIN:}
